project_id = "rrrnnrjefyffllnrwhkz"

[functions.delete-account]
verify_jwt = false

[functions.fix-terminal-transactions]
verify_jwt = false

[functions.parse-bank-statement]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false
