// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-transactions.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_transactions_default = defineTool({
  name: "list_transactions",
  title: "Listar lan\xE7amentos",
  description: "Lista lan\xE7amentos financeiros (receitas/despesas) do usu\xE1rio autenticado no EVA OS. Aceita filtros de intervalo de data de pagamento, tipo e status. Ordenado por data desc.",
  inputSchema: {
    start_date: z.string().describe("Data inicial de payment_date (YYYY-MM-DD). Opcional.").optional(),
    end_date: z.string().describe("Data final de payment_date (YYYY-MM-DD). Opcional.").optional(),
    type: z.enum(["receita", "despesa"]).describe("Filtrar por tipo.").optional(),
    status: z.enum(["Pago", "Pendente"]).describe("Filtrar por status.").optional(),
    limit: z.number().int().min(1).max(200).describe("M\xE1x. de resultados (padr\xE3o 50).").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date, type, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("transactions").select(
      "id, description, amount, type, status, payment_date, competence_date, category, subcategory, contact_name, bank_account_id, credit_card_id, wallet_id"
    ).order("payment_date", { ascending: false }).limit(limit ?? 50);
    if (start_date) q = q.gte("payment_date", start_date);
    if (end_date) q = q.lte("payment_date", end_date);
    if (type) q = q.eq("type", type);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { transactions: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/create-transaction.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_transaction_default = defineTool2({
  name: "create_transaction",
  title: "Criar lan\xE7amento",
  description: "Cria um lan\xE7amento (receita ou despesa) no EVA OS para o usu\xE1rio autenticado. Vincule a uma conta banc\xE1ria, cart\xE3o ou carteira usando list_accounts para obter o ID.",
  inputSchema: {
    description: z2.string().min(1).describe("Descri\xE7\xE3o do lan\xE7amento."),
    amount: z2.number().positive().describe("Valor absoluto (positivo)."),
    type: z2.enum(["receita", "despesa"]).describe("Tipo do lan\xE7amento."),
    payment_date: z2.string().describe("Data de pagamento (YYYY-MM-DD)."),
    status: z2.enum(["Pago", "Pendente"]).describe("Status. Padr\xE3o: Pago.").optional(),
    category: z2.string().describe("Categoria (texto livre ou UUID de categoria).").optional(),
    contact_name: z2.string().describe("Nome do contato/fornecedor/cliente.").optional(),
    notes: z2.string().describe("Observa\xE7\xF5es.").optional(),
    bank_account_id: z2.string().uuid().describe("ID da conta banc\xE1ria.").optional(),
    credit_card_id: z2.string().uuid().describe("ID do cart\xE3o de cr\xE9dito.").optional(),
    wallet_id: z2.string().uuid().describe("ID da carteira.").optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const { data, error } = await supabase.from("transactions").insert({
      user_id: ctx.getUserId(),
      description: input.description,
      amount: input.amount,
      type: input.type,
      payment_date: input.payment_date,
      competence_date: input.payment_date,
      status: input.status ?? "Pago",
      category: input.category ?? null,
      contact_name: input.contact_name ?? null,
      notes: input.notes ?? null,
      bank_account_id: input.bank_account_id ?? null,
      credit_card_id: input.credit_card_id ?? null,
      wallet_id: input.wallet_id ?? null
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Lan\xE7amento criado: ${data.id}` }],
      structuredContent: { transaction: data }
    };
  }
});

// src/lib/mcp/tools/list-accounts.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_accounts_default = defineTool3({
  name: "list_accounts",
  title: "Listar contas",
  description: "Lista todas as contas do usu\xE1rio: contas banc\xE1rias, cart\xF5es de cr\xE9dito e carteiras. Retorna os IDs necess\xE1rios para create_transaction.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    const [banks, cards, wallets] = await Promise.all([
      supabase.from("bank_accounts").select("id, name, bank_name, initial_balance"),
      supabase.from("credit_cards").select("id, name, brand, closing_day, due_day"),
      supabase.from("wallets").select("id, name, initial_balance")
    ]);
    const payload = {
      bank_accounts: banks.data ?? [],
      credit_cards: cards.data ?? [],
      wallets: wallets.data ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_categories_default = defineTool4({
  name: "list_categories",
  title: "Listar categorias",
  description: "Lista todas as categorias do usu\xE1rio (receitas e despesas) com hierarquia.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser4(ctx);
    const { data, error } = await supabase.from("categories").select("id, name, type, parent_id, cost_center, icon").order("name");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { categories: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/financial-summary.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var financial_summary_default = defineTool5({
  name: "financial_summary",
  title: "Resumo financeiro",
  description: "Retorna resumo financeiro do per\xEDodo: total de receitas, despesas, saldo, e breakdown por categoria. Considera apenas lan\xE7amentos com status Pago.",
  inputSchema: {
    start_date: z3.string().describe("Data inicial do per\xEDodo (YYYY-MM-DD)."),
    end_date: z3.string().describe("Data final do per\xEDodo (YYYY-MM-DD).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser5(ctx);
    const { data, error } = await supabase.from("transactions").select("amount, type, category").eq("status", "Pago").gte("payment_date", start_date).lte("payment_date", end_date).limit(5e3);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    let receitas = 0;
    let despesas = 0;
    const byCategory = {};
    for (const t of data ?? []) {
      const amount = Number(t.amount) || 0;
      const cat = t.category || "Sem categoria";
      byCategory[cat] ??= { receita: 0, despesa: 0 };
      if (t.type === "receita") {
        receitas += amount;
        byCategory[cat].receita += amount;
      } else {
        despesas += amount;
        byCategory[cat].despesa += amount;
      }
    }
    const summary = {
      period: { start_date, end_date },
      totals: {
        receitas: Number(receitas.toFixed(2)),
        despesas: Number(despesas.toFixed(2)),
        saldo: Number((receitas - despesas).toFixed(2))
      },
      by_category: Object.entries(byCategory).map(([category, v]) => ({
        category,
        receita: Number(v.receita.toFixed(2)),
        despesa: Number(v.despesa.toFixed(2))
      })).sort((a, b) => b.despesa + b.receita - (a.despesa + a.receita)),
      transaction_count: data?.length ?? 0
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "rrrnnrjefyffllnrwhkz";
var mcp_default = defineMcp({
  name: "eva-os-mcp",
  title: "EVA OS",
  version: "0.1.0",
  instructions: "Ferramentas para gest\xE3o financeira no EVA OS. Use list_accounts e list_categories para descobrir IDs antes de criar lan\xE7amentos. Use financial_summary para relat\xF3rios de per\xEDodo e list_transactions para consultas detalhadas.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_transactions_default, create_transaction_default, list_accounts_default, list_categories_default, financial_summary_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
